version: '3.4'

services:

#-------------Services------------------
  catalog-api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile   
  
  basket-api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount-api:
    image: ${DOCKER_REGISTRY-}discount
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile


#-------------Infra------------------
  catalog-db:
    image: mongo

  basket-cache:
    image: redis:alpine

  discount-db:
    image: postgres


#------------Volumes----------------
volumes:
  mongo_data:
  postgres_data:  
  
